food = input("Name a food:")
plant = input("Name a type of plant:")
cooking = input("Name a method of cooking")       
burned = input("What word describes burned food?")
diy = input("Name a DIY item")
print("Menu")
print(cooking,food,"with",burned,plant,"on a bed of", diy)