myName = input("Name:")
myFood = input("Favorite Food:")
myMusic = input("Favorite Music:")
myLive = input("Where do you live:")
print(myName,"loves to eat",myFood,",listens to",myMusic,",and lives in,",myLive)